# Generated by Django 5.0.3 on 2024-05-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'published'), ('d', 'draft')], max_length=1, null=True),
        ),
    ]
