# Generated by Django 5.0.3 on 2024-05-28 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.BooleanField()),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Artigo'},
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='criado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='publicado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'publicado'), ('d', 'draft')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titulo'),
        ),
    ]
