# Generated by Django 5.0.3 on 2024-05-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_catagory_alter_article_options_alter_article_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='catagory',
            field=models.ManyToManyField(to='blog.catagory', verbose_name='categoria'),
        ),
    ]
